### ISSUE TITLE
tizWati not loading

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/prakriya#213]
A local checking showed the following bug

```
>>> p.get_info('tizWati')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/http/drdhaval2785/DhavalPhD/scripts/my_env/lib/python3.11/site-packages/prakriya/verbforms.py", line 214, in get_info
    return self.__getitem__(items)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/http/drdhaval2785/DhavalPhD/scripts/my_env/lib/python3.11/site-packages/prakriya/verbforms.py", line 200, in __getitem__
    data = self.get_data(verbform, self.tar, 'slp1', self.outTran)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/http/drdhaval2785/DhavalPhD/scripts/my_env/lib/python3.11/site-packages/prakriya/verbforms.py", line 180, in get_data
    return storeresult(data, inTran, outTran, self.sutrainfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/http/drdhaval2785/DhavalPhD/scripts/my_env/lib/python3.11/site-packages/prakriya/verbforms.py", line 263, in storeresult
    sutratext = sutrainfo[member['sutra_num']]
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'par@56-1'
```

It turns out that the file sutrainfo does not have `par@56-1` but has `par@56.1`  and hence the error.

**Comment by drdhaval2785** [comment]
I think there may be other cases too, where I may need to modify the sutrainfo file, or provide for a more graceful exit message instead of breaking the system.
